version: "2.3"

#Compose pour dev

services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cdp
  backend:
    build: ./back-src
    volumes:
      - ./back-src:/home/node
      - /home/node/node_modules
    command: npm run docker-dev
    environment:
      - NODE_ENV=development
      - AUTH_SECRET=46399AD6FCB4BCCC172E395E759B82B532AB8422FD7C737FE440D68479C6C8CF
    ports:
      - "3000:3000"
    init: true
    links:
      - db
  frontend:
    build: ./front-src
    volumes:
      - ./front-src:/home/node
      - /home/node/node_modules
    command: npm start
    ports:
      - "4200:4200"
    init: true
    links:
      - backend
  proxy:
    image: nginx
    ports:
      - '3200:80'
    volumes:
      - ./reverse-proxy-src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - frontend
